### ISSUE TITLE
Fails often when tested in parallel

### ISSUE THREAD

**Issue by andk** [OpusVL/OpenERP-XMLRPC-Simple#1]
As per subject. Reason seems to be a hardcoded server port. Diagnostics always contains 'Address already in use'.

Unfortunately my cpan smoking servers are often running tests with several perls at the same time, so are provoking this error more often. I just let 8 perls run sequentially through this test and all passed it, among them 4 that had previously failed the test.

I should probably put this distro on a blacklist, because I cannot easily prevent that tests run in parallel on the same host. Or the test can be emended to pick a free port?

Wat do you think?

**Comment by colinnewell** [comment]
I should probably be able to fix it.  Thanks for reporting it.

**Comment by colinnewell** [comment]
I believe I have really fixed this this time.  The library had an automatic scan for free port option, but I didn't read the documentation properly (or test it properly) and didn't actually use it.

**Comment by andk** [comment]
>>>>> On Sat, 03 Sep 2016 04:51:42 -0700, colinnewell <notifications@github.com> said:

  > Closed #1.

Very nice, my smoker counts 39 pass, 0 fail

Thank You && Regards,
-- 
andreas
